name: Build

on:
  push:
    branches:
      - 'py*'

jobs:
  Build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run pre-commit hooks
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      - name: Login to Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment variables
        run: |
          echo "IMAGE_NAME=ghcr.io/$GITHUB_REPOSITORY" >> $GITHUB_ENV
          echo "IMAGE_HASH=${GITHUB_SHA:0:8}" >> $GITHUB_ENV

      - name: Build image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          platforms: linux/amd64
          context: ./python/
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_HASH }}
          push: true
