name: Build

on:
  push:
    branches:
      - 'py*'

jobs:
  Build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment variables
        run: |
          echo "IMAGE_NAME=ghcr.io/$GITHUB_REPOSITORY" >> $GITHUB_ENV
          echo "IMAGE_HASH=${GITHUB_SHA:0:8}" >> $GITHUB_ENV

      - name: Build image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          platforms: linux/amd64
          context: ./python/
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_HASH }}
          push: true
